### ISSUE TITLE
kaldialign-0.3 install failed

### ISSUE THREAD

**Issue by xiangxyq** [pzelasko/kaldialign#4]
Hi, 
when using 'pip install --verbose kaldialign' install kaldialign, failed to install 0.3 version, finally version 0.2 install successfully.  logs:

Using pip 21.2.4 from /opt/conda/lib/python3.9/site-packages/pip (python 3.9)
Collecting kaldialign
  Downloading kaldialign-0.3.tar.gz (10 kB)
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5vs591nx/kaldialign_3f7ed57b6e6d4a979465eb5b17e32acb/setup.py", line 111, in <module>
        f.write(f"__version__ = '{get_package_version()}'\n")
      File "/tmp/pip-install-5vs591nx/kaldialign_3f7ed57b6e6d4a979465eb5b17e32acb/setup.py", line 102, in get_package_version
        with open("CMakeLists.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'CMakeLists.txt'
WARNING: Discarding https://files.pythonhosted.org/packages/06/4d/cddae8f15576630c55aeadd58631d400eb366358581dd7b57e0896cba6f0/kaldialign-0.3.tar.gz#sha256=071d16089f206d6c11025858fff78bb1991b2eaea718ff13a0d9d9e69a7107ef (from https://pypi.org/simple/kaldialign/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading kaldialign-0.2.tar.gz (39 kB)
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-uvo1szfh/kaldialign.egg-info
    writing /tmp/pip-pip-egg-info-uvo1szfh/kaldialign.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-uvo1szfh/kaldialign.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-uvo1szfh/kaldialign.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-uvo1szfh/kaldialign.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-uvo1szfh/kaldialign.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-uvo1szfh/kaldialign.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    writing manifest file '/tmp/pip-pip-egg-info-uvo1szfh/kaldialign.egg-info/SOURCES.txt'
Building wheels for collected packages: kaldialign
  Running command /opt/conda/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5vs591nx/kaldialign_5cb4433a854e4cb6b79bdc79fdb925d8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5vs591nx/kaldialign_5cb4433a854e4cb6b79bdc79fdb925d8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ss39jva6
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/extensions
  copying extensions/__init__.py -> build/lib.linux-x86_64-3.9/extensions
  running build_ext
  building 'kaldialign' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/extensions
  gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/tmp/pip-install-5vs591nx/kaldialign_5cb4433a854e4cb6b79bdc79fdb925d8/extensions -I/opt/conda/include/python3.9 -c extensions/align.cpp -o build/temp.linux-x86_64-3.9/extensions/align.o -std=c++11 -Wno-register -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
  gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/tmp/pip-install-5vs591nx/kaldialign_5cb4433a854e4cb6b79bdc79fdb925d8/extensions -I/opt/conda/include/python3.9 -c extensions/kaldi_align.cpp -o build/temp.linux-x86_64-3.9/extensions/kaldi_align.o -std=c++11 -Wno-register -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
  g++ -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -shared -Wl,-rpath,/opt/conda/lib -Wl,-rpath-link,/opt/conda/lib -L/opt/conda/lib -Wl,-rpath,/opt/conda/lib -Wl,-rpath-link,/opt/conda/lib -L/opt/conda/lib build/temp.linux-x86_64-3.9/extensions/align.o build/temp.linux-x86_64-3.9/extensions/kaldi_align.o -o build/lib.linux-x86_64-3.9/kaldialign.cpython-39-x86_64-linux-gnu.so
  /opt/conda/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/extensions
  copying build/lib.linux-x86_64-3.9/extensions/__init__.py -> build/bdist.linux-x86_64/wheel/extensions
  copying build/lib.linux-x86_64-3.9/kaldialign.cpython-39-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
  running install_egg_info
  running egg_info
  writing kaldialign.egg-info/PKG-INFO
  writing dependency_links to kaldialign.egg-info/dependency_links.txt
  writing requirements to kaldialign.egg-info/requires.txt
  writing top-level names to kaldialign.egg-info/top_level.txt
  reading manifest file 'kaldialign.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file 'kaldialign.egg-info/SOURCES.txt'
  Copying kaldialign.egg-info to build/bdist.linux-x86_64/wheel/kaldialign-0.2-py3.9.egg-info
  running install_scripts
  adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
  creating build/bdist.linux-x86_64/wheel/kaldialign-0.2.dist-info/WHEEL
  creating '/tmp/pip-wheel-ss39jva6/kaldialign-0.2-cp39-cp39-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'kaldialign.cpython-39-x86_64-linux-gnu.so'
  adding 'extensions/__init__.py'
  adding 'kaldialign-0.2.dist-info/LICENSE'
  adding 'kaldialign-0.2.dist-info/METADATA'
  adding 'kaldialign-0.2.dist-info/WHEEL'
  adding 'kaldialign-0.2.dist-info/top_level.txt'
  adding 'kaldialign-0.2.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for kaldialign (setup.py) ... done
  Created wheel for kaldialign: filename=kaldialign-0.2-cp39-cp39-linux_x86_64.whl size=34661 sha256=9207ced32458ee21917bcba83b5d369dc19c0c040a41685b338b035b51aefa30
  Stored in directory: /root/.cache/pip/wheels/ab/6e/ec/548bcab54d6c93f3a31ab3283cbad1e8512fd14c05b5d1ce20
Successfully built kaldialign
Installing collected packages: kaldialign
Successfully installed kaldialign-0.2

**Comment by somniumism** [comment]
I'm dealing with the same problem as you. I want to build the Docker image in `icefall`, but no `CMakeLists.txt` found from version 0.3.
```
Step 8/10 : RUN git clone https://github.com/k2-fsa/icefall /workspace/icefall && 	cd /workspace/icefall && 	pip install -r requirements.txt
 ---> Running in c7878173aedc
Cloning into '/workspace/icefall'...
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting kaldilm
  Downloading kaldilm-1.13.tar.gz (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 kB 8.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting kaldialign
  Downloading kaldialign-0.3.tar.gz (10 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9bykkuml/kaldialign_b2fddaefd195433ea5eb1a44223ea4a7/setup.py", line 111, in <module>
          f.write(f"__version__ = '{get_package_version()}'\n")
        File "/tmp/pip-install-9bykkuml/kaldialign_b2fddaefd195433ea5eb1a44223ea4a7/setup.py", line 102, in get_package_version
          with open("CMakeLists.txt") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'CMakeLists.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
The command '/bin/sh -c git clone https://github.com/k2-fsa/icefall /workspace/icefall && 	cd /workspace/icefall && 	pip install -r requirements.txt' returned a non-zero code: 1
```

**Comment by ahmedalbahnasawy** [comment]
Same Error here. after installing it from the source
`   
import _kaldialign
ModuleNotFoundError: No module named '_kaldialign'
`

**Comment by csukuangfj** [comment]
> Same Error here. after installing it from the source

@ahmedalbahnasawy what is your operating system?

**Comment by csukuangfj** [comment]
@xiangxyq 
https://github.com/pzelasko/kaldialign/pull/5 should fix your issue.

**Comment by somniumism** [comment]
@xiangxyq The problem was just resolved. You can install and use `kaldialign-0.4` from now on.
